#!/bin/bash

alias ..="cd .."
alias gs="grep -Rn --exclude=*.svn*"
alias gl="grep -Rl --exclude=*.svn*"

repl() {
	screen -S repl $1
}

ff() {
	find . -type f -iname "*$1*" -not -name "*.svn*" 
}

ft() {
	find . -type f -iname "*.$1" -not -name "*.svn*" 
}

fd() { 
	find . -type d -iname "*$1*" -not -name "*.svn*" 
}

vv() {
	eval "$@" | vim -
}

ww() {
	if [ "$1" != "" ]; then
		cd $1;
		export WORK_DIR=`pwd`;
	else
		cd $WORK_DIR;
	fi
}
